olark.declare({name:"Cobrowsing",version:"1.0",startup:function(j,d){function e(b){if(d.locale.hasOwnProperty(b)&&d.locale[b])return d.locale[b];if(k.hasOwnProperty(b))return k[b];return"MISSING TRANSLATION: "+b}function g(b){return hbl.util.encode_html_entities(e(b))}function l(b){var c=this;b=b||{};this._api=b.legacyOlarkAPI;this._win=b.window||window;this._doc=this._win.document;this._accountToken=b.accountToken;this._apiToken=b.apiToken;this._libraryURL=b.libraryURL;this._silent=b.silent;this._maskedSelectors=
b.maskedSelectors;this._showSecureElements=b.showSecureElements;this._conversationId=b.conversationId;this._calls=[];this._checkFireflyTimer=null;this._currentSessionName=this._api.data.getConversationObject({key:"currentSessionName"});this._currentSessionName.get()||this._currentSessionName.set((new Date).getTime());this._connectionTimer=null;this._waitingForAccept=this._connecting=!1;this._active=this._api.data.getConversationObject({key:"active"});this._active.get()&&this._ensureFireflyIsAvailable();
this._declined=this._api.data.getConversationObject({key:"declined"});this._ended=this._api.data.getConversationObject({key:"ended"});this._lastURL=this._api.data.getConversationObject({key:"lastURL"});this._operatorName=null;this._api.chat.onMessageToVisitor(function(a){c._operatorName=a.message.nickname});this.on("cobrowsingEnded",function(){c._notifyOperator(e("cobrowsing_notify_operator_end_text"));c._notifyVisitor(g("cobrowsing_notify_visitor_end_text"));c._clearConnection()});this.on("repControlRequested",
function(){if(c._silent)c.grantRepControl(!0);else{var a=confirm(e("cobrowsing_confirm_control_text"));a&&c._notifyVisitor(g("cobrowsing_notify_visitor_control_text"));c.grantRepControl(a)}});this.set("theme","black");this.set("whitelabel",!0);this._maskSecureFields();this._api.chat.__SPI_onInterfaceElementReady(function(a){c._populateInterface(a.key,a.dom)});this._api.chat.__SPI_onEndedStateChanged(function(){c._active.get()&&c._endSession()})}var m=["on","set","startAPI","grantRepControl"],k={cobrowsing_notify_visitor_end_text:"Cobrowsing has ended.",
cobrowsing_confirm_control_text:"Would you like the operator to take control of your browser?",cobrowsing_notify_visitor_control_text:"The operator is now controlling your browser.",cobrowsing_visitor_confirm_allow_message:"Do you want to allow the operator to view your browser window?",cobrowsing_visitor_confirm_allow_button_start:"Start sharing.",cobrowsing_visitor_confirm_allow_button_decline:"Decline.",cobrowsing_visitor_allow_approve_message:"You're now sharing your browser.",cobrowsing_allow_approve_button_stop:"End sharing.",
cobrowsing_notify_visitor_decline_text:"Cobrowsing declined.",cobrowsing_notify_visitor_browser_not_supported:"We are sorry, but it looks like your internet browser does not support cobrowsing. Cobrowsing is currently only available in modern browsers.",cobrowsing_notify_operator_browser_not_supported:"We are sorry, but it looks like the visitor's internet browser does not support cobrowsing. Cobrowsing is currently only available in modern browsers.",cobrowsing_notify_operator_end_text:"Visitor has ended cobrowsing.",
cobrowsing_notify_operator_decline_text:"The visitor has declined the cobrowse session.",cobrowsing_notify_operator_slow_connection_text:"Looks like connecting with the browser is going slowly, please contact us if this happens often",cobrowsing_notify_operator_start_conversation_text:"Please start a conversation before requesting to share the visitors browser window.",cobrowsing_notify_operator_share_link_text:"See what they see",cobrowsing_notify_operator_waiting_to_accept_text:"Waiting for visitor to accept cobrowsing...",
cobrowsing_notify_operator_connecting_text:"Connecting with the visitor's browser...",cobrowsing_notify_operator_decline_share_text:"The visitor declined the cobrowsing session.",cobrowsing_notify_operator_unable_to_start_text:"Unable to start cobrowsing session, please contact us if this happens often"};(function(b){for(var c in m)(function(a){b[a]=function(){this._calls.push({method:a,args:arguments});this._dequeueCalls()}})(m[c]);b._isSupported=function(){return window.document.querySelector&&
window.document.querySelectorAll};b.debug=function(a){return this._debugMode=a};b.share=function(){j.chat.__SPI_isConversing()||this._debugMode?(this._declined.set(!1),this._ended.set(!1),this._ensureSharing(),this._debugMode&&this._startSharing()):this._notifyOperator(e("cobrowsing_notify_operator_start_conversation_text"))};b._ensureSharing=function(){this._ensureFireflyIsAvailable();if(this._lastURL.get())this._notifyOperator(e("cobrowsing_notify_operator_share_link_text")+" ==> "+this._lastURL.get());
else if(this._isSupported()){if(this._notifyOperator(e("cobrowsing_notify_operator_waiting_to_accept_text")),!this._waitingForAccept)this._waitingForAccept=!0,this._createInterface("confirmation-box-"+this._currentSessionName.get())}else olark._.hlog("#cobrowsing_not_supported"),this._notifyOperator(e("cobrowsing_notify_operator_browser_not_supported")),this._notifyVisitor(g("cobrowsing_notify_visitor_browser_not_supported"))};b._startSharing=function(){var a=this;this._ensureFireflyIsAvailable();
this._currentSessionName.set((new Date).getTime());this._notifyOperator(e("cobrowsing_notify_operator_connecting_text"));this._startConnection();try{this.startAPI(this._apiToken,{suppressUI:!0,partnerSessionID:this._conversationId},function(b){olark._.hlog("#cobrowsing_session_starting");a._clearConnection();a._active.set(!0);if(b){var n=b.replace(/.*olark\.usefirefly\.com\//,"https://static.olark.com/view/#");a._notifyOperator(e("cobrowsing_notify_operator_share_link_text")+" ==> "+n);a._lastURL.set(b);
a._createInterface("cobrowse-terminate-"+a._currentSessionName.get());olark._.hlog("#cobrowsing_session_started")}else a._notifyOperator(e("cobrowsing_notify_operator_decline_share_text"))})}catch(b){window.console&&window.console.warn&&(window.console.warn("[olark] unable to start cobrowsing session: "+b),olark._.hlog("#cobrowsing_exception "+b)),this._notifyOperator(e("cobrowsing_notify_operator_unable_to_start_text")+": beta+cobrowsing@olark.com")}};b._notifyOperator=function(a){this._debugMode?
window.console&&console.info&&console.info("[cobrowse] would have notified operator:",a):this._api.chat.sendNotificationToOperator({body:a})};b._notifyVisitor=function(a){this._api.chat.sendNotificationToVisitor({body:a})};b._createInterface=function(a){this._api.chat.__SPI_sendInterfaceElementToVisitor({key:a})};b._populateInterface=function(a,b){var f=this,e=a.split("-").pop();switch(!0){case /^confirmation\-box\-/i.test(a):b.innerHTML=g("cobrowsing_visitor_confirm_allow_message")+" <span style='display:block;text-align:right;'><button data-action='start'>"+
g("cobrowsing_visitor_confirm_allow_button_start")+"</button><button data-action='decline'>"+g("cobrowsing_visitor_confirm_allow_button_decline")+"</button></span>";for(var c=b.querySelectorAll("button"),d=0;d<c.length;d++){var i=c[d];if(f._declined.get()||f._active.get()||f._ended.get())i.disabled=!0;if(e!=f._currentSessionName.get())i.disabled=!0;i.onclick=function(a){a=a||window.event;(a.target||a.srcElement).attributes["data-action"].value==="start"?f._lastURL.get()||f._handleConfirmation.apply(f,
[a]):f._handleDecline.apply(f,[a]);for(a=0;a<c.length;a++)c[a].disabled=!0}}break;case /^cobrowse\-terminate\-/i.test(a):b.innerHTML=g("cobrowsing_visitor_allow_approve_message")+"<span style='display:block;text-align:right;'><button>"+g("cobrowsing_allow_approve_button_stop")+"</button></span>";d=b.querySelector("button");if(this._declined.get()||!this._active.get()||!this._ended.get())d.disabled=!0;if(e!=f._currentSessionName.get())d.disabled=!0;d.onclick=function(a){a=a||window.event;var b=a.target||
a.srcElement;f._handleStop.apply(f,[a]);b.disabled=!0}}};b._handleConfirmation=function(){olark._.hlog("#cobrowsing_session_requested");this._waitingForAccept=!1;this._startSharing();return!1};b._handleDecline=function(){olark._.hlog("#cobrowsing_session_declined");this._waitingForAccept=!1;this._notifyOperator(e("cobrowsing_notify_operator_decline_text"));this._notifyVisitor(g("cobrowsing_notify_visitor_decline_text"));this._declined.set(!0);this._currentSessionName.set((new Date).getTime());return!1};
b._handleStop=function(){olark._.hlog("#cobrowsing_session_stopped");this._endSession();return!1};b._endSession=function(){var a=this._firefly();a&&this._active.get()&&(a.endSession(),this._clearConnection())};b._ensureFireflyIsAvailable=function(){var a=this._firefly();if(!a||a.token!==this._accountToken&&!a.hasOwnProperty("ready")){window.fireflyAPI={token:this._accountToken};a=this._doc.createElement("script");a.type="text/javascript";a.src=this._libraryURL;a.async=!0;var b=this._doc.getElementsByTagName("script")[0];
b.parentNode.insertBefore(a,b)}};b._firefly=function(){return window.fireflyAPI};b._ready=function(){var a=this._firefly();return a&&a.startAPI?!0:!1};b._dequeueCalls=function(){if(this._ready())for(var a=this._firefly();this._calls.length;){var b=this._calls.shift();a[b.method].apply(a,b.args)}else if(!this._checkFireflyTimer){var f=this;this._checkFireflyTimer=setTimeout(function(){f._checkFireflyTimer=null;f._dequeueCalls()},1E3)}};b._startConnection=function(){var a=this;this._connecting=!0;this._connectionTimer=
setTimeout(function(){a._connecting&&(a._notifyOperator(e("cobrowsing_notify_operator_slow_connection_text")+": beta+cobrowsing@olark.com"),a._clearConnection(),olark._.hlog("#cobrowsing_session_timeout"))},11E3)};b._clearConnection=function(){this._connecting=!1;clearTimeout(this._connectionTimer);this._connectionTimer=null;this._lastURL.set(null);this._active.set(!1);this._declined.set(!1);this._ended.set(!0)};b._forEachDomElement=function(a,b){for(var f=document.querySelectorAll(a),c=0;c<f.length;c++)b(f[c])};
b._maskSecureFields=function(){function a(a,b){var c=b.toLowerCase(),d=b.toUpperCase(),e=b.replace(/([^a-z0-9]|\b)([a-z0-9])/ig,function(a,b,c){return b+c.toUpperCase()});return["["+a+"*="+c+"]","["+a+"*="+d+"]","["+a+"*="+e+"]"].join(",")}var b=this._maskedSelectors;b=b.concat([a("name","Ecom_Payment"),a("name","credit_card"),a("name","creditcard"),a("type","hidden"),a("type","password"),a("name","hidden"),a("name","password"),a("name","secret"),a("name","auth"),a("name","token")]);this._showSecureElements&&
this._forEachDomElement(b.join(","),function(a){a.style.boxShadow="0 0 8px yellow"});this.set("masking",{"*":b})}})(l.prototype);var o=new window.olark.__core.BrowserTab({idStorageKey:"olark.activeBrowserTab"}),h=new l({legacyOlarkAPI:j,accountToken:d.system.firefly_account_token||"507dd5f985dbad354701c5b6",apiToken:d.system.firefly_api_token||"507dd5f988a1113547000001",libraryURL:d.system.firefly_library_url||"https://firefly-071591.s3.amazonaws.com/scripts/loaders/loader.js",silent:d.system.prompt_visitor_for_cobrowsing||
!1,maskedSelectors:d.system.masked_selectors_for_cobrowsing||[],showSecureElements:d.system.show_secure_cobrowsing_elements,conversationId:olark._.conversationId});olark("api.chat.onCommandFromOperator",function(b){b.command.name==="see"&&o.active()&&(olark._.hlog("#cobrowsing_session_requested"),h.debug(!1),h.share())});olark._.triggerFireflyDebug=function(){h.debug(!0);h.share()}}});
